sudu: required
language: node_js
node_js:
- node
service:
- docker
script:
- npm install
- npm run build
- docker build -t grantmcdade/hello-kubernetes .
- docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push grantmcdade/hello-kubernetes
env:
  global:
    secure: D+PsSBWs5tSlPhsRq5Bn8+BCfHhE/SCfO9VuBs9xZabXgYdeJ3ZodQeOl79SvKhvawozcbF4BvnpEOsHgezOm9+o2Nn9gYYWaeX4flx5MvtNGRTHuMdH4Hr6JTiewvwKkZTh1c8NG2yHYdtn4cOFyY/6a3QaNutAn1Xn7YGBZtObnLRIUkM3XUrH5ykuqht/NvwO6iqTM9LGEkCHQCVmQt6kGfkrJ4tUc7MUJKHFtiSgmI7vgv5TGWso6QhnL0vXh2VnofzqIx9YkDdkmGTVdHs7ycBg79pHjDyA5qhafl3OSdcOcEhqchm19NfvcL5LAeNdKySWdtPIaNiup8yHbX++kOc7Id+YlQ8o97AsGF81x033V31EU6PsPhrOIpo6/9O106940v9Z7bht+/BCkEVssvzhJF1sa4R4LMHBeX24zJFUHXgWvoLFDv9XNf1BtVXRZUN8AX23LIXpPv1HY19rpocWYNWl5INn6JNme4weXP/COrJ5/IMT38Z8WtLFMN2Kfh6IBpZzdxZH4CSKtPYDIMJPPNdpoD/ECn0KrSsNQIaDax6QazVHcxbKEaLhaeOD4UHc4tq40QnP/2/21u4NGZKzvYzYmlGn/BBJvx+FQJ97lFD70YSuju0oixl6J8BJv2gc1q2zAkPv9fGq8dk+xeverK6hghfjQjHBG/s=
