sudu: required
language: node_js
env:
  global:
    DOCKER_USERNAME: grantmcdade
    DOCKER_PASSWORD: Zg0nrEnr1LPXNgDNEbSdOIPVQ4U6QJRaDmEptiz+zephi0FfIVFUoiMTQcCSlCyZtygIfwwADAILQXtyfT3W5oXtR/daNYW0qo6pXUEqIrc3p1smOfGiyCGbgxtnKQvnA7pkACYJ7ylRMPIDJOyoH31nyq4kcHNNGF7P+YAj4PiRtKPwKUosSmx3hMh0lX4X269L0ifFEIysK5Wxc0+IlaGOIuhQYWuzD20pxkUapgdttbn4zOBtUdtvf0iFRsi3PrjFcGwTZHh7vPjiHcBY3N/r1hHgX9bvGZ22Z6qEfVs/6uh25HDbsrgehEZXQdYnHK09zS8MVyw+LH97MHP1cKKRSgPcF+LjMUslJ7Gt6WSqwINhi2nAdiDNLYWuwqTmpPFQ1HE6YVkCyWyfYPNPEsiVI4c76lojrJe4G6LkGE79twaZl5cBYPyTFI78aVlmQAl9o3Excp7gm1rARiPOJIOItv1a0zXbH7IE6oM73hVzk+2vd4FGItafi2ObQRz4Hc30JYx5C4LCp9kiHttfwc2xDwl/jYc8p2rqpF7A0yjDhZu3W2mnKWkK1XdNScEwSSyxcw8JEjnyTIB+CSeUcmhQS995SxVwVyq1aB1MJl8MXE3K+jatrFfJ1k3vkz88IisQ/eomEy7zn7X/i6z4/mDcoXVulkCt08x8OH5s7Rs=
node_js:
- node
service:
- docker
script:
- npm install
- npm run build
- docker build -t grantmcdade/hello-kubernetes .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push grantmcdade/hello-kubernetes
